### ISSUE TITLE
Figure out how to relative import mozphab?

### ISSUE THREAD

**Issue by pdehaan** [pdehaan/phabricator-pytest#2]
https://github.com/mozilla-conduit/review/blob/15d71924ede367e31a2ad6be64b06d6114e45967/tests/test_patch.py#L8-L10

This feels like an abyss.
https://docs.python.org/3/library/imp.html says that the **imp** class has been deprecated since python 3.4, and we should use **importlib** instead. But I can't find the correct python incantation to migrate that code.

Even using the deprecated code with a hardcoded local path to my `moz-phab` script, it looks like I see some vague error:

> mozphab_test.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> ...
> ModuleNotFoundError: No module named 'ConfigParser'

```py
import imp
import os

mozphab = imp.load_source(
    # "mozphab", os.path.join(os.path.dirname(__file__), os.path.pardir, "moz-phab")
    "mozphab", "/Users/pdehaan/dev/github/mozilla/phabricator/git-cinnabar/moz-phab"
)

print(mozphab)

"""
mozphab_test.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "mozphab_test.py", line 6, in <module>
    "mozphab", "/Users/pdehaan/dev/github/mozilla/phabricator/git-cinnabar/moz-phab"
  File "/Users/pdehaan/.local/share/virtualenvs/phabricator-pytest-dm0QBrpi/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/pdehaan/dev/github/mozilla/phabricator/git-cinnabar/moz-phab", line 19, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
"""
```

I see this, which implies that [`ConfigParser` (py 2.x)](https://docs.python.org/2/library/configparser.html#configparser.ConfigParser) was renamed to [`configparser` (py 3.x)](https://docs.python.org/3/library/configparser.html#ConfigParser.ConfigParser) lowercase, which may be a separate issue.

> **Note:** The `ConfigParser` module has been renamed to `configparser` in Python 3. The `2to3` tool will automatically adapt imports when converting your sources to Python 3.

**Comment by pdehaan** [comment]
Apparently mozphab only works in py2 as a module. I think the plan of action was to just go back to original idea of invoking the library via the terminal and capturing the output as needed.
